version: "3.1" # Form verson 3.1 we can use docker secrets

services:
  drupal_web: # Drupal CMS with php and apache
    image: drupal:8-apache
    ports:
      - "8000:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    networks:
      - drupalApp

  drupal_db: # Postgres database
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
      POSTGRES_USER: /run/secrets/psql_user
      PGDATA: '/var/lib/postgresql/data/pgdata'
    secrets:
      - psql_user
      - psql_password
    networks:
      - drupalApp

# Set a application custom network with static IP
networks:
  drupalApp:

# Create docker volumes to store services data
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  pgdata:

secrets:
  psql_user:
   external: true
  psql_password:
   external: true
