security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_INTERNET:              ROLE_INTERNET
        ROLE_ADMIN:                 ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        admin:
            provider: fos_userbundle
            pattern: ^/admin
            anonymous: true
            logout:
                path:   fos_user_security_logout
                target: /admin/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

    access_control:
        - { path: ^/admin/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login/check/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: [ ROLE_ADMIN ] }