security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_INTERNET:              ROLE_INTERNET
        ROLE_ADMIN:                 ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        db_provider:
            id: app.user_provider

    firewalls:
        admin:
            provider: fos_userbundle
            pattern: ^/admin
            anonymous: true
            logout:
                path:   fos_user_security_logout
                target: /admin/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            stateless: true
            pattern: ^/api/(?!token)
            provider: db_provider
            guard:
                authenticators:
                    - app.api_authenticator
        main:
            anonymous: ~

    access_control:
        - { path: ^/admin/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login/check/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: [ ROLE_ADMIN ] }
        - { path: ^/api/token, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/api/, roles: [ ROLE_USER, ROLE_ADMIN ] }